spring:
  config.activate.on-profile: local
  jpa:
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${Email_Id}
    password: ${Email_Pw}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWD}
    driver-class-name: ${DB_CLASS}
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2.client:
      registration:
        naver:
          clientId: ${naver_client_id}
          clientSecret: ${naver_client_secret}
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - nickname
            - email
            - profile_image
          clientName: Naver
        kakao:
          clientId: ${kakao_client_id}
          clientSecret: ${kakao_client_secret}
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id
springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html
  show-actuator: true

cloud:
  aws:
    stack.auto: false
    region.static: ap-northeast-2
ncp:
  accessKey: ${ncp_obj_access_key}
  secretKey: ${ncp_obj_secret_key}
  regionName: kr-standard
  endpoint: https://kr.object.ncloudstorage.com
  bucket: ${bucket}
jwt:
  secret_key: ${secret_key}
---
management:
  endpoints.web.exposure.include: "*"
spring:
  config.activate.on-profile: prod
  jpa:
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${Email_Id}
    password: ${Email_Pw}
    properties:
      mail.smtp:
        auth: true
        timeout: 5000
        starttls.enable: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWD}
    driver-class-name: ${DB_CLASS}
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2.client:
      registration:
        naver:
          clientId: ${naver_client_id}
          clientSecret: ${naver_client_secret}
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - nickname
            - email
            - profile_image
          clientName: Naver
        kakao:
          clientId: ${kakao_client_id}
          clientSecret: ${kakao_client_secret}
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      ## Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id
springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html
  show-actuator: true

jwt:
  secret_key: ${secret_key}

cloud:
  aws:
    stack.auto: false
    region.static: ap-northeast-2
ncp:
  accessKey: ${ncp_obj_access_key}
  secretKey: ${ncp_obj_secret_key}
  regionName: kr-standard
  endpoint: https://kr.object.ncloudstorage.com
  bucket: ${bucket}