spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${Email_Id}
    password: ${Email_Pw}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
