spring:
  config:
    activate:
      on-profile: dev
  jpa:
    open-in-view: false
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
---
spring:
  profiles:
    active: db
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password}
    driver-class-name: ${driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
