# 작업명
name: Auto deploy NCP

on:
  push:
    branches: "main"

jobs:
  push_to_registry:
    ## NCP OS : Ubuntu 20.04
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Main Branch Make application-prod.properties
        run: |
          cd ./src/main/resources
          touch ./application-prod.properties
          echo "${{ secrets.APPLICATION }}" > ./application-prod.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_API_KEY }}
          password: ${{ secrets.NCP_API_SECRET_KEY }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/weble-backend:latest

  pull_deploy:
    name: Connect server ssh and pull from container registry
    needs: push_to_registry
    runs-on: ubuntu-20.04
    steps:
      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          username: ${{ secrets.NCP_SERVER_NAME }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          port: 22
          script: |
            docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/weble:latest
            docker stop weble-backend || true
            docker rm weble-backend || true
            docker run -d --name weble-backend -p 8080:8080 ${{ secrets.NCP_CONTAINER_REGISTRY }}/weble:latest
            docker image prune -f
